CREATE TABLE BOARD
(
    BOARD_NO       NUMBER(10)	NOT NULL,
    BOARD_WRITER_NO       VARCHAR2(10),
    BOARD_TITLE         VARCHAR2(50),
    BOARD_CONTENT         VARCHAR2(1000),
    BOARD_ORIGINAL_FILENAME    VARCHAR2(100),
    BOARD_RENAMED_FILENAME     VARCHAR2(100),
    BOARD_READCOUNT        NUMBER(10),
    BOARD_STATUS      VARCHAR2(1),
    BOARD_CREATE_DATE	DATE,
    BOARD_UPDATE_DATE	DATE,
    BOARD_TYPE	VARCHAR2(20)

);
CONSTRAINT board_pk PRIMARY KEY (BOARD)


CREATE TABLE BOARD (
    NO NUMBER,
    WRITER_NO NUMBER,
	TITLE VARCHAR2(50),
	CONTENT VARCHAR2(2000),
	ORIGINAL_FILENAME VARCHAR2(100),
	RENAMED_FILENAME VARCHAR2(100),
	READCOUNT NUMBER DEFAULT 0,
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
    CREATE_DATE DATE DEFAULT SYSDATE,
    MODIFY_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT PK_BOARD_NO PRIMARY KEY(NO),
    CONSTRAINT FK_BOARD_WRITER FOREIGN KEY(WRITER_NO) REFERENCES MEMBER(NO) ON DELETE SET NULL
);

CREATE SEQUENCE SEQ_BOARD_NO;

CREATE TABLE REPLY(
  REPLY_NO NUMBER PRIMARY KEY,
  REPLY_BOARD_NO NUMBER,
  REPLY_WRITER_NO NUMBER,
  REPLY_CONTENT VARCHAR2(400),
  REPLY_STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
  REPLY_CREATE_DATE DATE DEFAULT SYSDATE,
  REPLY_MODIFY_DATE DATE DEFAULT SYSDATE,
  FOREIGN KEY (BOARD_NO) REFERENCES BOARD,
  FOREIGN KEY (WRITER_NO) REFERENCES MEMBER
);

CREATE SEQUENCE SEQ_REPLY_NO;