CREATE TABLE MEMBER (
    MEMBER_NO                NUMBER    PRIMARY KEY,
    MEMBER_ID                VARCHAR(30),
    MEMBER_PW                VARCHAR(300),
    MEMBER_NAME              VARCHAR(20),
    MEMBER_GENDER            VARCHAR(1),
    MEMBER_NICKNAME          VARCHAR(20),
    MEMBER_EMAIL             VARCHAR(30),
    MEMBER_IS                VARCHAR(1),
    MEMBER_TYPE              NUMBER,
    MEMBER_WARN              NUMBER,
    MEMBER_CREATE_DATE       DATE DEFAULT SYSDATE,
    MODIFY_DATE              DATE DEFAULT SYSDATE,
    MEMBER_PHOTO             VARCHAR(100),
    MEMBER_ADDRESS           VARCHAR(100),
    MEMBER_ZIPCODE           VARCHAR(10),
    MEMBER_DETAIL_ADDRESS    VARCHAR(100),
    MEMBER_SNS_ID            VARCHAR(100),
    MEMBER_ANIMAL_REG_NO     VARCHAR(15)
);

CREATE SEQUENCE SEQ_MEMBER_NO;

CREATE TABLE MEMBER_OUT (
    MEMBER_NO            NUMBER PRIMARY KEY,
    OUT_REASONS          VARCHAR(400),
    OUT_DATE             DATE DEFAULT SYSDATE
);

CREATE TABLE BOARD (
    BOARD_NO                   NUMBER,
    BOARD_WRITER_NO            NUMBER,
	BOARD_TITLE                VARCHAR2(50),
	BOARD_CONTENT              VARCHAR2(2000),
	BOARD_ORIGINAL_FILENAME    VARCHAR2(100),
	BOARD_RENAMED_FILENAME     VARCHAR2(100),
	BOARD_READCOUNT NUMBER     DEFAULT 0,
    BOARD_STATUS VARCHAR2(1)   DEFAULT 'Y' CHECK (BOARD_STATUS IN('Y', 'N')),
    BOARD_CREATE_DATE          DATE DEFAULT SYSDATE,
    BOARD_MODIFY_DATE          DATE DEFAULT SYSDATE,
    CONSTRAINT PK_BOARD_NO     PRIMARY KEY(BOARD_NO),
    CONSTRAINT FK_BOARD_WRITER FOREIGN KEY(BOARD_WRITER_NO) REFERENCES MEMBER(MEMBER_NO) ON DELETE SET NULL
);

CREATE SEQUENCE SEQ_BOARD_NO;

CREATE TABLE REPLY(
  REPLY_NO                      NUMBER PRIMARY KEY,
  REPLY_BOARD_NO                NUMBER,
  REPLY_WRITER_NO               NUMBER,
  REPLY_CONTENT                 VARCHAR2(400),
  REPLY_GROUP                   NUMBER,
  REPLY_GROUP_ORDER             NUMBER,
  REPLY_DEPTH                   NUMBER,
  REPLY_STATUS                  VARCHAR2(1) DEFAULT 'Y' CHECK (REPLY_STATUS IN ('Y', 'N')),
  REPLY_CREATE_DATE             DATE DEFAULT SYSDATE,
  REPLY_MODIFY_DATE             DATE DEFAULT SYSDATE,
  FOREIGN KEY (REPLY_BOARD_NO)  REFERENCES BOARD ON DELETE CASCADE,
  FOREIGN KEY (REPLY_WRITER_NO) REFERENCES MEMBER ON DELETE CASCADE
);

ALTER TABLE REPLY ADD(
      REPLY_PARENT NUMBER,
      REPLY_DEPTH NUMBER,
      REPLY_ORDER NUMBER
);

CREATE SEQUENCE SEQ_REPLY_NO;
