CREATE TABLE BOARD
(
    BOARD_NO       NUMBER(10)	NOT NULL,
    BOARD_WRITER_NO       VARCHAR2(10),
    BOARD_TITLE         VARCHAR2(50),
    BOARD_CONTENT         VARCHAR2(1000),
    BOARD_ORIGINAL_FILENAME    VARCHAR2(100),
    BOARD_RENAMED_FILENAME     VARCHAR2(100),
    BOARD_READCOUNT        NUMBER(10),
    BOARD_STATUS      VARCHAR2(1),
    BOARD_CREATE_DATE	DATE,
    BOARD_UPDATE_DATE	DATE,
    BOARD_TYPE	VARCHAR2(20)

);
CONSTRAINT board_pk PRIMARY KEY (BOARD)